; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:waveshare_esp32s3_43b]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200

board_build.arduino.memory_type = qio_opi
board_build.f_flash = 80000000L

board_build.flash_mode = qio
board_build.flash_size = 16MB
board_upload.flash_size = 16MB
board_build.psram_type = opi

build_src_filter = +<*> -<simulator_main.cpp>

; Plain esptool upload over the board's native USB-CDC serial interface (MI_00, COM5).
; JTAG debugging still available separately via the MI_02 interface + esp-builtin.
upload_protocol = esptool
upload_port = COM4
upload_speed = 921600
monitor_port = COM4

; Fix USB CDC COM Port disappearing on boot/crash
build_flags =
    -D BOARD_HAS_PSRAM
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=0
    -DLV_CONF_INCLUDE_SIMPLE
    -Iinclude
    -DESP_PANEL_CONF_PATH=ESP_Panel_Conf.h

lib_deps =
    lvgl/lvgl@^9.2.2
    ESP32_Display_Panel@^1.1.1
    ESP32_IO_Expander@^1.1.0

; ---------------------------------------------------------------------
; 💻 NATIVE WINDOWS EMULATOR TARGET (PC SIMULATOR WINDOW)
; ---------------------------------------------------------------------
[env:emulator_windows]
platform = native

; RENAME THIS LINE TO build_src_filter
build_src_filter = +<*> -<main.cpp>

build_flags =
    -D PC_SIMULATOR=1
    -D TFT_WIDTH=800
    -D TFT_HEIGHT=480
    
    -DLV_CONF_INCLUDE_SIMPLE
    -I"include"
    -I".pio/libdeps/emulator_windows/lvgl/src"
    -I".pio/libdeps/emulator_windows/lvgl"
    
    -lSDL2
    -I"F:/msys64/ucrt64/include/SDL2"
    -L"F:/msys64/ucrt64/lib"
    
lib_deps =
    lvgl/lvgl@^9.2.2

