#pragma once

#define ESP_PANEL_BOARD_DEFAULT_USE_CUSTOM (1)
#define ESP_PANEL_USE_LCD 1
#define ESP_PANEL_LCD_COLOR_BITS_RGB565 16

#define ESP_PANEL_BOARD_NAME "Waveshare:ESP32-S3-Touch-LCD-4.3-B"
#define ESP_PANEL_BOARD_WIDTH 800
#define ESP_PANEL_BOARD_HEIGHT 480

#define ESP_PANEL_BOARD_USE_LCD 1
#define ESP_PANEL_BOARD_LCD_CONTROLLER ST7262
#define ESP_PANEL_BOARD_LCD_BUS_TYPE ESP_PANEL_BUS_TYPE_RGB
#define ESP_PANEL_BOARD_LCD_RGB_USE_CONTROL_PANEL 0
#define ESP_PANEL_BOARD_LCD_RGB_CLK_HZ (16 * 1000 * 1000)
#define ESP_PANEL_BOARD_LCD_RGB_HPW 4
#define ESP_PANEL_BOARD_LCD_RGB_HBP 8
#define ESP_PANEL_BOARD_LCD_RGB_HFP 8
#define ESP_PANEL_BOARD_LCD_RGB_VPW 4
#define ESP_PANEL_BOARD_LCD_RGB_VBP 8
#define ESP_PANEL_BOARD_LCD_RGB_VFP 8
#define ESP_PANEL_BOARD_LCD_RGB_PCLK_ACTIVE_NEG 1
#define ESP_PANEL_BOARD_LCD_RGB_DATA_WIDTH 16
#define ESP_PANEL_BOARD_LCD_RGB_PIXEL_BITS ESP_PANEL_LCD_COLOR_BITS_RGB565
#define ESP_PANEL_BOARD_LCD_RGB_BOUNCE_BUF_SIZE (ESP_PANEL_BOARD_WIDTH * 10)
#define ESP_PANEL_BOARD_LCD_RGB_IO_HSYNC 46
#define ESP_PANEL_BOARD_LCD_RGB_IO_VSYNC 3
#define ESP_PANEL_BOARD_LCD_RGB_IO_DE 5
#define ESP_PANEL_BOARD_LCD_RGB_IO_PCLK 7
#define ESP_PANEL_BOARD_LCD_RGB_IO_DISP -1
#define ESP_PANEL_BOARD_LCD_RGB_IO_DATA0 14
#define ESP_PANEL_BOARD_LCD_RGB_IO_DATA1 38
#define ESP_PANEL_BOARD_LCD_RGB_IO_DATA2 18
#define ESP_PANEL_BOARD_LCD_RGB_IO_DATA3 17
#define ESP_PANEL_BOARD_LCD_RGB_IO_DATA4 10
#define ESP_PANEL_BOARD_LCD_RGB_IO_DATA5 39
#define ESP_PANEL_BOARD_LCD_RGB_IO_DATA6 0
#define ESP_PANEL_BOARD_LCD_RGB_IO_DATA7 45
#define ESP_PANEL_BOARD_LCD_RGB_IO_DATA8 48
#define ESP_PANEL_BOARD_LCD_RGB_IO_DATA9 47
#define ESP_PANEL_BOARD_LCD_RGB_IO_DATA10 21
#define ESP_PANEL_BOARD_LCD_RGB_IO_DATA11 1
#define ESP_PANEL_BOARD_LCD_RGB_IO_DATA12 2
#define ESP_PANEL_BOARD_LCD_RGB_IO_DATA13 42
#define ESP_PANEL_BOARD_LCD_RGB_IO_DATA14 41
#define ESP_PANEL_BOARD_LCD_RGB_IO_DATA15 40
#define ESP_PANEL_BOARD_LCD_COLOR_BITS ESP_PANEL_LCD_COLOR_BITS_RGB565
#define ESP_PANEL_BOARD_LCD_COLOR_BGR_ORDER 0
#define ESP_PANEL_BOARD_LCD_COLOR_INEVRT_BIT 0
#define ESP_PANEL_BOARD_LCD_SWAP_XY 0
#define ESP_PANEL_BOARD_LCD_MIRROR_X 0
#define ESP_PANEL_BOARD_LCD_MIRROR_Y 0
#define ESP_PANEL_LCD_SWAP_XY 0
#define ESP_PANEL_LCD_MIRROR_X 0
#define ESP_PANEL_LCD_MIRROR_Y 0
#define ESP_PANEL_LCD_INEVRT_COLOR 0
#define ESP_PANEL_BOARD_LCD_GAP_X 0
#define ESP_PANEL_BOARD_LCD_GAP_Y 0
#define ESP_PANEL_BOARD_LCD_RST_IO -1
#define ESP_PANEL_BOARD_LCD_RST_LEVEL 0

#define ESP_PANEL_LCD_NAME ST7262
#define ESP_PANEL_LCD_CONTROLLER ST7262
#define ESP_PANEL_LCD_CONTROLLER_ST7262 1
#define ESP_PANEL_LCD_BUS_TYPE ESP_PANEL_BUS_TYPE_RGB
#define ESP_PANEL_LCD_BUS_NAME RGB
#define ESP_PANEL_LCD_BUS_SKIP_INIT_HOST 1
#define ESP_PANEL_LCD_H_RES ESP_PANEL_BOARD_WIDTH
#define ESP_PANEL_LCD_V_RES ESP_PANEL_BOARD_HEIGHT
#define ESP_PANEL_LCD_RGB_CLK_HZ (16 * 1000 * 1000)
#define ESP_PANEL_LCD_RGB_HPW 4
#define ESP_PANEL_LCD_RGB_HBP 8
#define ESP_PANEL_LCD_RGB_HFP 8
#define ESP_PANEL_LCD_RGB_VPW 4
#define ESP_PANEL_LCD_RGB_VBP 8
#define ESP_PANEL_LCD_RGB_VFP 8
#define ESP_PANEL_LCD_RGB_IO_DISP -1
#define ESP_PANEL_LCD_RGB_IO_DE 5
#define ESP_PANEL_LCD_RGB_IO_HSYNC 46
#define ESP_PANEL_LCD_RGB_IO_VSYNC 3
#define ESP_PANEL_LCD_RGB_IO_PCLK 7
#define ESP_PANEL_LCD_RGB_IO_DATA0 14
#define ESP_PANEL_LCD_RGB_IO_DATA1 38
#define ESP_PANEL_LCD_RGB_IO_DATA2 18
#define ESP_PANEL_LCD_RGB_IO_DATA3 17
#define ESP_PANEL_LCD_RGB_IO_DATA4 10
#define ESP_PANEL_LCD_RGB_IO_DATA5 39
#define ESP_PANEL_LCD_RGB_IO_DATA6 0
#define ESP_PANEL_LCD_RGB_IO_DATA7 45
#define ESP_PANEL_LCD_RGB_IO_DATA8 48
#define ESP_PANEL_LCD_RGB_IO_DATA9 47
#define ESP_PANEL_LCD_RGB_IO_DATA10 21
#define ESP_PANEL_LCD_RGB_IO_DATA11 1
#define ESP_PANEL_LCD_RGB_IO_DATA12 2
#define ESP_PANEL_LCD_RGB_IO_DATA13 42
#define ESP_PANEL_LCD_RGB_IO_DATA14 41
#define ESP_PANEL_LCD_RGB_IO_DATA15 40
#define ESP_PANEL_LCD_SPI_CLK_HZ 1000000
#define ESP_PANEL_LCD_SPI_IO_CS -1
#define ESP_PANEL_LCD_SPI_IO_SCL -1
#define ESP_PANEL_LCD_SPI_IO_SDA -1
#define ESP_PANEL_LCD_SPI_MODE 0
#define ESP_PANEL_LCD_WIDTH ESP_PANEL_BOARD_WIDTH
#define ESP_PANEL_LCD_HEIGHT ESP_PANEL_BOARD_HEIGHT
#define ESP_PANEL_LCD_COLOR_BITS ESP_PANEL_LCD_COLOR_BITS_RGB565
#define ESP_PANEL_LCD_RGB_DATA_WIDTH 16
#define ESP_PANEL_LCD_RGB_DATA_GPIO0 14
#define ESP_PANEL_LCD_RGB_DATA_GPIO1 38
#define ESP_PANEL_LCD_RGB_DATA_GPIO2 18
#define ESP_PANEL_LCD_RGB_DATA_GPIO3 17
#define ESP_PANEL_LCD_RGB_DATA_GPIO4 10
#define ESP_PANEL_LCD_RGB_DATA_GPIO5 39
#define ESP_PANEL_LCD_RGB_DATA_GPIO6 0
#define ESP_PANEL_LCD_RGB_DATA_GPIO7 45
#define ESP_PANEL_LCD_RGB_DATA_GPIO8 48
#define ESP_PANEL_LCD_RGB_DATA_GPIO9 47
#define ESP_PANEL_LCD_RGB_DATA_GPIO10 21
#define ESP_PANEL_LCD_RGB_DATA_GPIO11 1
#define ESP_PANEL_LCD_RGB_DATA_GPIO12 2
#define ESP_PANEL_LCD_RGB_DATA_GPIO13 42
#define ESP_PANEL_LCD_RGB_DATA_GPIO14 41
#define ESP_PANEL_LCD_RGB_DATA_GPIO15 40
#define ESP_PANEL_LCD_RGB_PCLK_GPIO 7
#define ESP_PANEL_LCD_RGB_HSYNC_GPIO 46
#define ESP_PANEL_LCD_RGB_VSYNC_GPIO 3
#define ESP_PANEL_LCD_RGB_DE_GPIO 5
#define ESP_PANEL_LCD_RGB_PCLK_ACTIVE_NEG 1
#define ESP_PANEL_LCD_RGB_HSYNC_IDLE_LOW 0
#define ESP_PANEL_LCD_RGB_VSYNC_IDLE_LOW 0
#define ESP_PANEL_LCD_RGB_DE_IDLE_HIGH 1
#define ESP_PANEL_LCD_RGB_TIMING_FREQ_HZ (16 * 1000 * 1000)
#define ESP_PANEL_LCD_RGB_TIMING_HPW 4
#define ESP_PANEL_LCD_RGB_TIMING_HBP 8
#define ESP_PANEL_LCD_RGB_TIMING_HFP 8
#define ESP_PANEL_LCD_RGB_TIMING_VPW 4
#define ESP_PANEL_LCD_RGB_TIMING_VBP 8
#define ESP_PANEL_LCD_RGB_TIMING_VFP 8

#define ESP_PANEL_BOARD_USE_TOUCH 0
#define ESP_PANEL_BOARD_USE_BACKLIGHT 1
#define ESP_PANEL_BOARD_BACKLIGHT_TYPE ESP_PANEL_BACKLIGHT_TYPE_SWITCH_EXPANDER
#define ESP_PANEL_BOARD_BACKLIGHT_IO 2
#define ESP_PANEL_BOARD_BACKLIGHT_ON_LEVEL 1
#define ESP_PANEL_BOARD_BACKLIGHT_IDLE_OFF 0

// Touch (GT911), shares the CH422G expander's I2C bus (SCL=9, SDA=8) at address 0x5D.
#define ESP_PANEL_USE_LCD_TOUCH 1
#define ESP_PANEL_LCD_TOUCH_CONTROLLER_GT911 1
#define ESP_PANEL_LCD_TOUCH_BUS_TYPE ESP_PANEL_BUS_TYPE_I2C
#define ESP_PANEL_LCD_TOUCH_BUS_HOST_ID 0
#define ESP_PANEL_LCD_TOUCH_BUS_SKIP_INIT_HOST 1
#define ESP_PANEL_LCD_TOUCH_I2C_CLK_HZ (400 * 1000)
#define ESP_PANEL_LCD_TOUCH_I2C_SCL_PULLUP 1
#define ESP_PANEL_LCD_TOUCH_I2C_SDA_PULLUP 1
#define ESP_PANEL_LCD_TOUCH_I2C_IO_SCL 9
#define ESP_PANEL_LCD_TOUCH_I2C_IO_SDA 8
#define ESP_PANEL_LCD_TOUCH_SWAP_XY 0
#define ESP_PANEL_LCD_TOUCH_MIRROR_X 0
#define ESP_PANEL_LCD_TOUCH_MIRROR_Y 0
#define ESP_PANEL_LCD_TOUCH_IO_RST -1
#define ESP_PANEL_LCD_TOUCH_IO_INT -1

#define ESP_PANEL_BOARD_USE_EXPANDER 1
#define ESP_PANEL_BOARD_EXPANDER_CHIP CH422G
#define ESP_PANEL_BOARD_EXPANDER_SKIP_INIT_HOST 0
#define ESP_PANEL_BOARD_EXPANDER_I2C_HOST_ID 0
#define ESP_PANEL_BOARD_EXPANDER_I2C_CLK_HZ (400 * 1000)
#define ESP_PANEL_BOARD_EXPANDER_I2C_SCL_PULLUP 1
#define ESP_PANEL_BOARD_EXPANDER_I2C_SDA_PULLUP 1
#define ESP_PANEL_BOARD_EXPANDER_I2C_IO_SCL 9
#define ESP_PANEL_BOARD_EXPANDER_I2C_IO_SDA 8
#define ESP_PANEL_BOARD_EXPANDER_I2C_ADDRESS 0x20

#define ESP_PANEL_BOARD_EXPANDER_POST_BEGIN_FUNCTION(p) \
	{ \
		auto board = static_cast<Board *>(p); \
		auto expander = static_cast<esp_expander::CH422G *>(board->getIO_Expander()->getBase()); \
		expander->enableAllIO_Output(); \
		return true; \
	}

#define ESP_PANEL_BOARD_LCD_PRE_BEGIN_FUNCTION(p) \
	{ \
		auto board = static_cast<Board *>(p); \
		auto expander = board->getIO_Expander()->getBase(); \
		expander->digitalWrite(3, 0); \
		vTaskDelay(pdMS_TO_TICKS(10)); \
		expander->digitalWrite(3, 1); \
		vTaskDelay(pdMS_TO_TICKS(100)); \
		return true; \
	}

#define ESP_PANEL_BOARD_CUSTOM_FILE_VERSION_MAJOR 1
#define ESP_PANEL_BOARD_CUSTOM_FILE_VERSION_MINOR 0
#define ESP_PANEL_BOARD_CUSTOM_FILE_VERSION_PATCH 0
